language: ruby
rvm:
- 2.4
cache: bundler
script: "./scripts/build.sh"
deploy:
  provider: pages
  skip_cleanup: true
  github-token: "$GITHUB_TOKEN"
  keep-history: true
  local_dir: _site
  on: master
  fqdn: turtlecoin.lol
  verbose: true
env:
  global:
  - secure: S2XAjweOYp3WHFeIfXhAztzfabOk+hLcC3hm3cLkpT3L9lM/mm5kOBgdW0tkEkoB9cwgCTEzddLK3qUYJtJyb28Wg4aJv/9wlDJ6kR5iqAQRoJXHIBFVSqX4e0W38B1DaG4u+Z0MOcHvMYluCZSD13L7kZp9nYCTl9RQJEAQGyYjAQcalzOCb3EyzGF+kMl7ZSJIc/zvC0dOx8OpHZ61BAmDxf5FsqBC829Ec6glQnFdl2Ez03rpkrMbx5QQqEFzO1o8GZYSQZH+wLnhA5lB3DjEW2Vh7InFiIUbQXNY6rHWEUhBVk4QVIXxgRkC59BlVdp0e2OjNQwPD7UfFkYiOyb4U4mJGnpTRcO2UgBfbm1m1EQPJcmXyIFyU3apVog8STtgoEQz25N2ZM3xwyX1DOR53qDLVv6k0rqXQkAt9cXg2VWsZ97w1w6AP2ZYcE0Bz9ONXUyZL2QBuBrqiF4Ab9nLXH5PRkXCr+qses+FgDIHyKT2xIY4sXQ4w+narD1NvjbHGkpq/KCntnWy9xkmazUtvzMj1x4U5wu9AR6+NBZbe7nmsNPuqgsQ6LdX5vb6Jpg10brn0CRJBn+xgs17BLAJFocsLjKq8FSYV1va5ysG1ndMzcfXVjMK+EPFJn2Mk9KsQZtq/wcOtkUXEsxxfCRYkeAs0pFOjRQzpJRGNSc=
  - secure: bTdOWoBMp9fX9Mm9KseOjAqwLxW/z1sa7XhtRyz46JX46eLGrEUG11I1Yo4eCzqNsgajch6/mMtN+QaTmakWhB27/kwDBaBZaZRS+PeSSjAAH0GIMsT5iWqd5/iFu1+o53XOwObWg2J1vznQXJMjgDHIZsSZgT5DkKL95OwS+LpSq538pc7n7jxFCc1cSPgGYvuKNY5YHdYsvoY1siLHuKljDBqHQVMzVf2S5uwGKC0V0mFy91mBdm9hgVkGq63g2U89Er/i7WdRS3lEeoTMXetDtztg//5LFIB1VdaDuNhXu5bKxHU5dxQ6oCaLq6LInB8pWDtHdOYwKYyKnSW8/4uryCpVUZujfrvNpqMKDeZG+99po8NxfxFfhERjo2WuNLm9AKsAw4QxtqPMY+MOqG9YKXg7EGNbWEVfMvacHDhBV+79XGaYRSipkcYlz2Kp7vHx0sN4rRYAwtVvC5Q5amQXNAzy3AhG62j3i5FSwplg9SWGe/cepkIiapc6LUd/1gF44lea/G+Bh75RzUULKVc0umaN/nIexmSWTiMy+TXW21Jp3ohL4HE7qx8akt88W+3XqE7OrXIbxnB8Jia3i0W5KVYOWnQHyAGfkMkrrC1s/JYLtKZyA/AQ3K5lcoLPlkXA2LRLL6gRNRFDA3/M6P7Q9eGEv2OJ0NdvqdS1UPE=
