# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
 exclude:
   - Gemfile
   - Gemfile.lock
   - scripts
   - README.md
   - vendor
