baseurl: ""

# Do not copy these files to the build folder
exclude:
 - Gemfile
 - Gemfile.lock
 - scripts
 - README.md
 - .bundle
 - vendor

gems:
 - jekyll-multiple-languages-plugin

languages: ["en", "de"]
exclude_from_localizations: ["assets", "js", "images", "css", "fonts", "scripts"]
